### PR TITLE
Remove fade-in animation and fix first frame flashing

### PR DESCRIPTION
**Pull request by tianenpang**
Solved the remaining problem in issue #8 about first frame flashing, for a better experience, fade-in animations have been removed.

At first, I wanted to use the segments attribute in Lottie to dynamically assign values ​​based on checked, so that the first frame can be skipped when checked is true, but the segments attribute in Lottie seems to have some problems.  and i decided to manually set the segments attribute in Lottie based on the checked attribute, also it can run perfectly.

### CODE REVIEW

**Comment by cawfree** [comment]
Hey @TianenPang, sorry I missed your message. After making the update I immediately passed out. 😂

Really excited to try this out! I’ve had a lot of trouble getting segments to work so I was under the impression they were a no-go for us. I’ll check this out later tonight. Thank you!

(Also, if you’ve cracked segments this could mean that we can really simplify the animation logic altogether!) 🥳

**Comment by tianenpang** [comment]
Hi @cawfree 

I also spent a lot of time on segments. 😂

After trying many ways, i find out that we can set the segments manually when we need (on dark mode is default).

Please check this when you have time. 

Thank you. 👍

**Comment by cawfree** [comment]
@TianenPang, this is awesome! I don't know how you did it, but it works flawlessly. Great job!

Also, I've _never_ seen this before:

```javascript
<
  {...null}
/>
```

Really surprised that works! 

I'll get this merged up and republish. Thanks again for your awesome work!

**Comment by cawfree** [comment]
[0.0.8](https://www.npmjs.com/package/react-dark-mode-toggle/v/0.0.8)

**Comment by tianenpang** [comment]
Thanks @cawfree 😊

```javascript
{...data}
```
This is called Spread syntax (...)

**Comment by cawfree** [comment]
No worries @TianenPang!

I never knew it worked for `null`! I always assumed attempts to spread a non-object would cause bad things to happen. Great to know! 🥳

**Comment by tianenpang** [comment]
Ah,  it's worked, haha 😀

By the way @cawfree, i have a question is about [this line](https://github.com/cawfree/react-dark-mode-toggle/commit/99b00e41163830a0cd91ad7ec8e9497038edb36a#diff-1fdf421c05c1140f6d71444ea2b27638R31) `ref.current.anim.advanceTime(1000)` where is this `1000` from?

**Comment by cawfree** [comment]
So originally it was a value I was using to force `speed` to quickly progress to the end of the animation, but then instead of modifying `speed` I used `advanceTime` instead. I wanted to use `Number.MAX_SAFE_INTEGER` but then bad things happen.

**Comment by tianenpang** [comment]
Is there a calculation formula for this value? because this value is a serious bug! 

We can't change speed, the animation will wrong when speed is changed (except default `speed = 1.3`) , because now `ref.current.anim.advanceTime(1300)` is for `speed = 1.3` only.

**Comment by cawfree** [comment]
I'll just pull this down again and take a look. Hopefully we can do without this line altogether now we're using segments?

**Comment by tianenpang** [comment]
I am working on it. 😂

**Comment by cawfree** [comment]
I believe the following seems to work consistently:

```javascript
useEffect(
  () => {
     /* force */
     (!!checked) && ref.current.anim.advanceTime(speed * 1000);
  },
  [],
);
```

**Comment by cawfree** [comment]
Ouch, scratch that. Fails for `speed={0.1}`.

**Comment by cawfree** [comment]
By the way, you may find this [documentation](https://github.com/airbnb/lottie-web/blob/master/player/js/animation/AnimationItem.js) useful!

**Comment by tianenpang** [comment]
Thanks,  I’ll take a look this. 👍

**Comment by cawfree** [comment]
Okay, this seems to work for all speeds:

```
/* force */
(!!checked) && ref.current.anim.setCurrentRawFrameValue(30);
```

Can you give this a try and if it's suitable, we'll republish.

**Comment by tianenpang** [comment]
OK

**Comment by tianenpang** [comment]
Hey @cawfree ,

Thanks for your advice `(!!checked) && ref.current.anim.setCurrentRawFrameValue(30);`

Already submit a pr #11, please check out.

**Pull request merged**
