### PR TITLE
add className as a prop

### PR DESCRIPTION
**Pull request by JorgePasco1**
#13 I thought this was a good idea, and pretty easy to implement. Just added className as a prop, and passed it as the className for the button. I also updated the README and added a comma that was missing in my previous contribution 😉

### CODE REVIEW

**Comment by cawfree** [comment]
Hey @JorgePasco1, thanks a lot for the contribution! Sorry for the delay in getting back to you. I'll just take a look at this now.

**Review by cawfree — APPROVED** [review]
Looks great. Many thanks!

**Comment by cawfree** [comment]
#13 [0.0.10](https://github.com/cawfree/react-dark-mode-toggle/commit/3a474cd4edb1310a1ae57266a2840cc39f9cf505).

**Comment by ElmouradiAmine** [comment]
Thanks for the contribution!

**Pull request merged**
