### PR TITLE
allow strings as size prop

### PR DESCRIPTION
**Pull request by JorgePasco1**
Hello! 👋. Thanks for this awesome component! I think allowing the user to use em and rems for the size prop would be a nice touch, so I added some lines to allow for it. Also updated the README, both for the new possible types, and for correcting the default in the table, which was displaying 80 (when the component had a defaultProp of 85) 😉

### CODE REVIEW

**Comment by cawfree** [comment]
Dude this is awesome! Thank you! Just wondering, do you know if there's a library we can depend on to manage the size unit parsing for us? It might be a bit easier to achieve compliance that way? I feel like there must be some existing logic somewhere in React that should be capable of doing this for us...

**Comment by JorgePasco1** [comment]
True! there must be, gonna look for it later and update the PR.

**Comment by JorgePasco1** [comment]
@cawfree refactored to use [parse-unit](https://www.npmjs.com/package/parse-unit) for parsing, now any css unit can be used👍. The force-pushes are due to some dumb mistakes, and I didn't want to have irrelevant commits. Take a look at it!

**Comment by cawfree** [comment]
Haha, I **love** that the library name was the same as your function.

Okay, this looks brilliant. I'll quickly pull this down and play around, and if everything looks okay (I'm sure it will be!) I'll publish a new version.

Thanks again!

**Comment by cawfree** [comment]
Okay, looks like `parse-unit` hasn't been added to the `package.json`, so just a small thing.

Just made the `size="100%"` and it looks awesome! Nice job! So if you can just modify the `package.json` we should be good to go. 🚀

**Comment by JorgePasco1** [comment]
Done! It was actually added as a dev-dependency, I swapped it to dependencies.

**Comment by JorgePasco1** [comment]
Done! It was actually added as a dev dependency haha, I swapped it out.

**Comment by cawfree** [comment]
Downloaded and retested, works perfectly!

Once again, thank you for your great work. I've always wondered how to go about including these kinds of units, so I greatly appreciate you taking the time out to teach me. I'll just merge and publish momentarily.

**Comment by cawfree** [comment]
Published as [v0.0.6](https://www.npmjs.com/package/react-dark-mode-toggle/v/0.0.6).

Thank you!

**Comment by JorgePasco1** [comment]
That’s great to hear! Thank you for the hospitality and for the awesome component again, glad to have been able to contribute.

**Comment by JorgePasco1** [comment]
By the way, just out of curiosity, what are those values in the margin, height, etc. (0.47, 1.65, ...)

**Comment by cawfree** [comment]
@JorgePasco1 Originally, the animation is a fixed box with some padding around it; these just help us wrap the component as tightly as possible so it interacts with the surrounding DOM in a sensible way. Sketchy, I know. 😝

**Pull request merged**
